name: organic
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^8.1.4+2
  flutter_search_bar: ^2.1.0
  confirm_dialog: ^1.0.0
  image_cropper: ^1.4.0
  brasil_fields: ^1.1.1
  carousel_pro: ^1.0.0
  image_picker: ^0.8.3+3
  after_layout: ^1.1.0
  url_launcher: ^6.0.3
  validadores: ^1.0.2
  backdrop: ^0.6.0
  provider: ^6.0.0
  confetti: ^0.5.5
  shimmer: ^2.0.0
  graphql: ^5.0.0
  geolocator: ^7.6.0
  flutter_secure_storage: ^4.2.1
  intl: ^0.17.0
  dio: ^4.0.0
  in_app_purchase: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sad images/abacate triste.png
    - assets/sad images/abobora triste.png
    - assets/sad images/brocolis triste.png
    - assets/sad images/cenoura triste.png
    - assets/sad images/tomate triste.png

    - assets/categories/Animais.jpg
    - assets/categories/Especiarias.jpg
    - assets/categories/Frutas.jpg
    - assets/categories/Grãos.jpg
    - assets/categories/Hortaliças.jpg
    - assets/categories/Legumes.jpg
    - assets/categories/Mudas.jpg
    - assets/categories/Origem Animal.jpg
    - assets/categories/Sementes.jpg
    - assets/categories/Verduras.jpg

    - assets/tomate feliz.png
    - assets/destaque.png
    - assets/logo.png
